Update master to stable 0.1.3 (#2)
New features:
- Included -i, --install argument to add msh to .bashrc and set an enviromental variable
- Included -r, --remove argument to remove msh from .bashrc and unset the enviromental variable
- Functions can now be directly invoked from the file, before installation
- Added new section for numerical functions
- Added 'stoi', a wrapper for leading-zeros-string to integer converter
- Added 'next', a filename-generating function
Changed features:
- 'wipe' will now fully clear the terminal, instead of scrolling down like 'clear'
- Minor changes to text output
- Remade aliases into functions
Bug fixes:
- Fixed a bug when help message would be displayed on startup twice

diff --git a/mortonsh b/mortonsh
--- a/mortonsh
+++ b/mortonsh
@@ -1,94 +1,132 @@
 # Morton's Bash Pack
-# Latest Version: 0.1.2
+# Latest Version: 0.1.3
 # Last Edit: 20/05/21
+
+version="0.1.3"
 
 ### Self-commands
 mortonsh() {
   case "${1}" in
-  --help)
-    echo "Can't help you yet... Sorry!"
-	;;
-  -h)
-    echo "Can't help you yet... Sorry!"
-	;;
-  --version)
-    echo "Morton's Bash Pack, version 0.1.2"
-	;;
-  -v)
-    echo "Morton's Bash Pack, version 0.1.2"
-	;;
   --edit)
     vim ~/mortonsh
     ;;
   -e)
     vim ~/mortonsh
     ;;
+  --help)
+    msh -v
+    echo "Can't help you yet... Sorry!"
+    echo "If you've just downloaded msh, use it with -i or --install to automatically add it to your .bashrc file."
+    echo "If you want to remove msh from your machine, use it with -r or --remove to undo the installation, then remove file 'mortonsh'."
+    ;;
+  -h)
+    msh -v
+    echo "Can't help you yet... Sorry!"
+    echo "If you've just downloaded msh, use it with -i or --install to automatically add it to your .bashrc file."
+    echo "If you want to remove msh from your machine, use it with -r or --remove to undo the installation, then remove file 'mortonsh'."
+    ;;
+  --install)
+    [ -z "${MORTONSH}" ] && echo -e "#MSHBEGIN\nexport MORTONSH=1\n[ -f ~/mortonsh ] && . ~/mortonsh 0\n#MSHEND" >> .bashrc
+    echo "Mortonsh written to .bashrc."
+    ;;
+  -i)
+    [ -z "${MORTONSH}" ] && echo -e "#MSHBEGIN\nexport MORTONSH=1\n[ -f ~/mortonsh ] && . ~/mortonsh 0\n#MSHEND" >> .bashrc
+    echo "Mortonsh written to .bashrc."
+    ;;
+  --remove)
+    ! [ -z "${MORTONSH}" ] && sed -i -e "/^#MSHBEGIN$/,/^#MSHEND$/d;/^#MSHEND$/d;/^#MSHBEGIN$/d" .bashrc && unset MORTONSH
+    ;;
+  -r)
+    ! [ -z "${MORTONSH}" ] && sed -i -e "/^#MSHBEGIN$/,/^#MSHEND$/d;/^#MSHEND$/d;/^#MSHBEGIN$/d" .bashrc && unset MORTONSH
+    ;;
+  --version)
+    echo "Morton's Bash Pack, version ${version}"
+    ;;
+  -v)
+    echo "Morton's Bash Pack, version ${version}"
+    ;;
   --update)
     cp mortonsh mortonsh.backup
     local branch="${2}"
     [ -z "${2}" ] && branch="master"
     wget https://raw.github.com/MortonPL/mortonsh/$branch/mortonsh -O ~/mortonsh
-	;;
+    ;;
   -u)
     cp mortonsh mortonsh.backup
     local branch="${2}"
     [ -z "${2}" ] && branch="master"
     wget https://raw.github.com/MortonPL/mortonsh/$branch/mortonsh -O ~/mortonsh
-	;;
+    ;;
   *)
     echo "mortonsh: usage: [OPTION]..."
-	echo "Try 'mortonsh --help' for more information."
+    echo "Try 'mortonsh --help' for more information."
     ;;
   esac
 }
-msh() {
-  mortonsh $@
-}
+msh() { mortonsh $@; }
 ### Common commands
-alias zz="cd .."
-alias ll="ls -al"
-alias xx="clear"
-alias home="cd ~"
-alias wipe="cd ~ && clear"
+zz() { cd ..; }
+xx() { clear; }
+home() { cd ~; }
+wipe() { printf "\ec"; }
+
+### Numerical
+stoi() { echo $((10#$1)); }
 
 ### Files
-rn() {
-  mv "${1}" "${2}"
-}
-vish() {
-  vim "${1}" && chmod +x "${1}"
-}
-cphere() {
-  cp "${1}" $(basename "${1}")
-}
-cpthere() {
-  cp "$(basename "${1}") ${1}"
-}
-mvhere() {
-  mv "${1}" $(basename "${1}")
-}
-mvthere() {
-  mv "$(basename "${1}") ${1}"
-}
+rn() { mv "${1}" "${2}"; }
+vish() { vim "${1}" && chmod +x "${1}"; }
+cphere() { cp "${1}" $(basename "${1}"); }
+cpthere() { cp "$(basename "${1}") ${1}"; }
+mvhere() { mv "${1}" $(basename "${1}"); }
+mvthere() { mv "$(basename "${1}") ${1}"; }
 swap() {
-  mv "${1}" $(dirname "${2}")/$(basename "${1}")
-  mv "${2}" $(dirname "${1}")/$(basename "${2}")
+  mv "${1}" $(dirname "${2}")/$(basename "${1}"; )
+  mv "${2}" $(dirname "${1}")/$(basename "${2}"; )
+}
+next() {
+  local flaga=0
+  local flagb=0
+  local ext="${1##*.}";
+  local temp="${1%%$ext*}";
+  local num="${temp//[^0-9]/}";
+  local numval=$(stoi $num);
+  local oldval=$numval;
+  local name="${1%%$num*}";
+  local zeros=${#num};
+  shopt -s nullglob;
+  for file in $name*.$ext;
+  do
+    val="${file##$name}";
+    val="${val%%.$ext}";
+    temp="{1//[^0-9]/}";
+    if [[ $zeros -ne ${#val} || ${#temp} -le 0 ]]; then
+      continue
+    fi
+    val=$(stoi $val);
+    [[ $val -eq $numval ]] && flaga=1;
+    [[ $val -gt $numval ]] && numval=$val && flaga=0 && flagb=1;
+  done
+  if [[ $numval -eq $oldval && flaga -eq 0 ]]; then
+    numval=$((oldval))
+  fi
+  if [[ $flagb -eq 1 || $numval -eq $oldval && $flaga -eq 1 ]]; then
+    numval=$((numval+1))
+  fi
+  printf "%s%0${zeros}d.%s\n" $name $numval $ext;
 }
 
 ### WEiTI-exclusive
-galeraget() {
-  scp "${1}"@galera.ii.pw.edu.pl:~/"${2}" $(basename "${2}")
-}
-galeraput() {
-  scp "${1}" "${2}"@galera.ii.pw.edu.pl:~/$(basename "${2}")
-}
-galera() {
-  ssh "${1}"@galera.ii.pw.edu.pl
-}
+galera() { ssh "${1}"@galera.ii.pw.edu.pl; }
+galeraget() { scp "${1}"@galera.ii.pw.edu.pl:~/"${2}" $(basename "${2}"); }
+galeraput() { scp "${1}" "${2}"@galera.ii.pw.edu.pl:~/$(basename "${2}"); }
 
 ### Other
 xserver() {
   DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0 &
 }
+
+### You can run it from the file, too
+{ [ "${#}" -eq 0 ] && mortonsh -h; } || { [ "${1}" != "0" ] && "${@}"; }
 
 # EOF
